"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Calculator, FileText, Languages, LayoutDashboard, LoaderCircle, PackageCheck, Plus, Search, Settings, Trash2, Truck, WalletCards, X } from "lucide-react";
import "./orders.css";

type Order = { id:string; orderNo:string; supplier:string; productName:string; source:string; sourceUrl:string; quantity:number; cnyAmount:number; exchangeRate:number; thaiExtraCost:number; expectedRevenue:number; status:string; note:string; createdAt:string };
const statuses=["รอชำระเงิน","ชำระแล้ว","กำลังผลิต","ส่งออกจากจีน","ถึงไทยแล้ว","ยกเลิก"];
const empty={supplier:"",productName:"",source:"1688",sourceUrl:"",quantity:1,cnyAmount:0,exchangeRate:4.65,thaiExtraCost:0,expectedRevenue:0,status:"รอชำระเงิน",note:""};
const nav=[[LayoutDashboard,"Dashboard","/dashboard"],[Calculator,"คำนวณต้นทุน","/"],[PackageCheck,"My China Orders","/orders"],[Languages,"ผู้ช่วยภาษาจีน","/assistant"],[FileText,"Supplier Book","/suppliers"],[WalletCards,"ชำระเงินหยวน","/payments"],[Truck,"ขนส่งจีน–ไทย","/shipping"]] as const;
const money=new Intl.NumberFormat("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2});

export default function OrdersPage(){
 const [orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showForm,setShowForm]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("ทั้งหมด"),[error,setError]=useState("");
 const [form,setForm]=useState(empty);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const res=await fetch("/api/orders");const data=await res.json();if(!res.ok)throw new Error(data.error);setOrders(data.orders)}catch(e){setError(e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ")}finally{setLoading(false)}},[]);
 useEffect(()=>{load();if(new URLSearchParams(location.search).get("new")==="1")setShowForm(true)},[load]);
 const filtered=useMemo(()=>orders.filter(o=>(filter==="ทั้งหมด"||o.status===filter)&&(`${o.orderNo} ${o.supplier} ${o.productName}`.toLowerCase().includes(query.toLowerCase()))),[orders,filter,query]);
 const summary=useMemo(()=>({total:orders.reduce((s,o)=>s+o.cnyAmount*o.exchangeRate+o.thaiExtraCost,0),open:orders.filter(o=>!["ถึงไทยแล้ว","ยกเลิก"].includes(o.status)).length,pending:orders.filter(o=>o.status==="รอชำระเงิน").reduce((s,o)=>s+o.cnyAmount*o.exchangeRate,0)}),[orders]);
 const set=(key:string,value:string|number)=>setForm(v=>({...v,[key]:value}));
 async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const res=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await res.json();if(!res.ok)throw new Error(data.error);setOrders(v=>[data.order,...v]);setForm(empty);setShowForm(false)}catch(e){setError(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}}
 async function updateStatus(id:string,status:string){const old=orders;setOrders(v=>v.map(o=>o.id===id?{...o,status}:o));const res=await fetch("/api/orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(!res.ok){setOrders(old);setError("เปลี่ยนสถานะไม่สำเร็จ")}}
 async function remove(id:string){setError("");const res=await fetch(`/api/orders?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(res.ok)setOrders(v=>v.filter(o=>o.id!==id));else setError("ลบออเดอร์ไม่สำเร็จ")}
 return <main className="shell orders-shell"><aside className="sidebar"><a className="brand" href="/dashboard"><img src="/wewalldifo-logo.png" alt="WEWALLDIFO Company Limited"/></a><p className="nav-title">เครื่องมือธุรกิจจีน</p><nav>{nav.map(([Icon,label,href],i)=><a key={label} className={i===2?"active":""} href={href}><Icon size={19}/>{label}</a>)}</nav><div className="sidebar-foot"><a href="#"><Settings size={19}/>ตั้งค่า</a><div className="profile"><span>T</span><div><strong>คุณตั้ม</strong><small>VW-000128</small></div></div></div></aside>
 <section className="workspace"><header><div className="mobile-logo"><img src="/wewalldifo-logo.png" alt="WEWALLDIFO"/></div><div className="today-rate"><span>เรท CNY วันนี้</span><b>¥1 = ฿4.65</b><small>อัปเดตล่าสุด 10:35</small></div><a className="account-link" href="/account">บัญชีของฉัน</a></header>
 <div className="orders-content"><div className="orders-heading"><div><small>MY CHINA ORDERS</small><h1>ออเดอร์สินค้าจีน</h1><p>บันทึกต้นทุนและติดตามสถานะทุกออเดอร์ในที่เดียว</p></div><button className="new-order" onClick={()=>setShowForm(true)}><Plus size={18}/>เพิ่มออเดอร์</button></div>
 <section className="orders-summary"><article><span>ต้นทุนรวมทั้งหมด</span><strong>฿{money.format(summary.total)}</strong></article><article><span>กำลังดำเนินการ</span><strong>{summary.open} รายการ</strong></article><article><span>ยอดรอชำระ</span><strong>฿{money.format(summary.pending)}</strong></article></section>
 {error&&<div className="order-error">{error}<button onClick={()=>setError("")}><X size={16}/></button></div>}
 {showForm&&<form className="order-form" onSubmit={create}><div className="form-head"><div><h2>เพิ่มออเดอร์ใหม่</h2><p>ระบบจะสร้างเลขออเดอร์ให้อัตโนมัติ</p></div><button type="button" onClick={()=>setShowForm(false)}><X/></button></div><div className="order-fields">
 <label><span>Supplier *</span><input required value={form.supplier} onChange={e=>set("supplier",e.target.value)} placeholder="ชื่อร้านหรือโรงงานจีน"/></label><label><span>ชื่อสินค้า *</span><input required value={form.productName} onChange={e=>set("productName",e.target.value)} placeholder="สินค้าที่สั่งซื้อ"/></label>
 <label><span>แหล่งที่มา</span><select value={form.source} onChange={e=>set("source",e.target.value)}><option>1688</option><option>Taobao</option><option>WeChat</option><option>โรงงานโดยตรง</option></select></label><label><span>ลิงก์สินค้า</span><input value={form.sourceUrl} onChange={e=>set("sourceUrl",e.target.value)} placeholder="https://..."/></label>
 <Num label="จำนวน" value={form.quantity} change={v=>set("quantity",v)}/><Num label="ยอดสินค้า (¥)" value={form.cnyAmount} change={v=>set("cnyAmount",v)}/><Num label="เรทหยวน" value={form.exchangeRate} change={v=>set("exchangeRate",v)}/><Num label="ค่าใช้จ่ายไทย (฿)" value={form.thaiExtraCost} change={v=>set("thaiExtraCost",v)}/><Num label="รายรับที่คาดไว้ (฿)" value={form.expectedRevenue} change={v=>set("expectedRevenue",v)}/>
 <label><span>สถานะ</span><select value={form.status} onChange={e=>set("status",e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="wide"><span>หมายเหตุ</span><textarea value={form.note} onChange={e=>set("note",e.target.value)} placeholder="รายละเอียดเพิ่มเติม"/></label></div><div className="form-actions"><button type="button" onClick={()=>setShowForm(false)}>ยกเลิก</button><button className="submit" disabled={saving}>{saving?<LoaderCircle className="spin" size={17}/>:<Plus size={17}/>}บันทึกออเดอร์</button></div></form>}
 <section className="orders-list"><div className="list-tools"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาออเดอร์ Supplier หรือสินค้า"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>ทั้งหมด</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
 {loading?<div className="order-empty"><LoaderCircle className="spin"/>กำลังโหลดออเดอร์</div>:filtered.length===0?<div className="order-empty"><PackageCheck/><strong>{orders.length?"ไม่พบรายการที่ค้นหา":"ยังไม่มีออเดอร์"}</strong><span>{orders.length?"ลองเปลี่ยนคำค้นหรือสถานะ":"กด “เพิ่มออเดอร์” เพื่อบันทึกรายการแรก"}</span></div>:<div className="orders-table-wrap"><table><thead><tr><th>เลขออเดอร์</th><th>Supplier / สินค้า</th><th>จำนวน</th><th>ยอดสินค้า</th><th>ต้นทุนประมาณ</th><th>สถานะ</th><th></th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td><b>{o.orderNo}</b><small>{new Date(o.createdAt).toLocaleDateString("th-TH")}</small></td><td><strong>{o.supplier}</strong><span>{o.productName} · {o.source}</span></td><td>{o.quantity.toLocaleString("th-TH")}</td><td><b>¥{money.format(o.cnyAmount)}</b></td><td><b>฿{money.format(o.cnyAmount*o.exchangeRate+o.thaiExtraCost)}</b></td><td><select className="status-select" value={o.status} onChange={e=>updateStatus(o.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td><button className="delete" onClick={()=>remove(o.id)} aria-label={`ลบ ${o.orderNo}`}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}</section></div></section></main>
}
function Num({label,value,change}:{label:string;value:number;change:(v:number)=>void}){return <label><span>{label}</span><input type="number" min="0" step="any" value={value} onChange={e=>change(Number(e.target.value))}/></label>}
