import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { paymentRequests } from "../../../db/schema";
const statuses=["รอตรวจสอบ","รอยืนยันยอด","กำลังดำเนินการ","ชำระสำเร็จ","ยกเลิก"];
const channels=["Alipay","WeChat Pay","บัญชีธนาคารจีน"];
const clean=(v:unknown)=>typeof v==="string"?v.trim():"";
export async function GET(){try{return Response.json({payments:await getDb().select().from(paymentRequests).orderBy(desc(paymentRequests.createdAt))})}catch(e){return Response.json({error:e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ"},{status:500})}}
export async function POST(req:Request){try{const b=await req.json() as Record<string,unknown>,recipient=clean(b.recipient),purpose=clean(b.purpose),amount=Number(b.cnyAmount),rate=Number(b.exchangeRate);if(!recipient||!purpose||!Number.isFinite(amount)||amount<=0)return Response.json({error:"กรุณากรอกผู้รับ วัตถุประสงค์ และจำนวนหยวนให้ครบ"},{status:400});const now=new Date(),id=crypto.randomUUID(),stamp=`${String(now.getFullYear()).slice(-2)}${String(now.getMonth()+1).padStart(2,"0")}${String(now.getDate()).padStart(2,"0")}`;const [payment]=await getDb().insert(paymentRequests).values({id,requestNo:`PAY-${stamp}-${id.slice(0,4).toUpperCase()}`,recipient,channel:channels.includes(clean(b.channel))?clean(b.channel):channels[0],account:clean(b.account),purpose,reference:clean(b.reference),cnyAmount:amount,exchangeRate:Number.isFinite(rate)&&rate>0?rate:4.65,status:"รอตรวจสอบ",note:clean(b.note),createdAt:now,updatedAt:now}).returning();return Response.json({payment},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"บันทึกไม่สำเร็จ"},{status:500})}}
export async function PATCH(req:Request){try{const b=await req.json() as Record<string,unknown>,id=clean(b.id),status=clean(b.status);if(!id||!statuses.includes(status))return Response.json({error:"ข้อมูลสถานะไม่ถูกต้อง"},{status:400});const [payment]=await getDb().update(paymentRequests).set({status,updatedAt:new Date()}).where(eq(paymentRequests.id,id)).returning();return payment?Response.json({payment}):Response.json({error:"ไม่พบคำขอ"},{status:404})}catch(e){return Response.json({error:e instanceof Error?e.message:"แก้ไขไม่สำเร็จ"},{status:500})}}
export async function DELETE(req:Request){try{const id=new URL(req.url).searchParams.get("id")?.trim();if(!id)return Response.json({error:"ไม่พบรหัสคำขอ"},{status:400});await getDb().delete(paymentRequests).where(eq(paymentRequests.id,id));return Response.json({success:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"ลบไม่สำเร็จ"},{status:500})}}
