"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Calculator, FileText, Languages, LayoutDashboard, LoaderCircle, PackageCheck, Plus, Search, Settings, Star, Trash2, Truck, WalletCards, X } from "lucide-react";
import "./suppliers.css";

type Supplier={id:string;name:string;contactName:string;platform:string;contact:string;shopUrl:string;category:string;rating:number;status:string;note:string;createdAt:string};
const statuses=["คู่ค้าหลัก","ใช้งานได้","กำลังทดลอง","งดใช้"];
const empty={name:"",contactName:"",platform:"1688",contact:"",shopUrl:"",category:"",rating:3,status:"กำลังทดลอง",note:""};
const nav=[[LayoutDashboard,"Dashboard","/dashboard"],[Calculator,"คำนวณต้นทุน","/"],[PackageCheck,"My China Orders","/orders"],[Languages,"ผู้ช่วยภาษาจีน","/assistant"],[FileText,"Supplier Book","/suppliers"],[WalletCards,"ชำระเงินหยวน","/payments"],[Truck,"ขนส่งจีน–ไทย","/shipping"]] as const;

export default function SuppliersPage(){
 const [items,setItems]=useState<Supplier[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showForm,setShowForm]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("ทั้งหมด"),[error,setError]=useState("");
 const [form,setForm]=useState(empty);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/suppliers"),d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.suppliers)}catch(e){setError(e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ")}finally{setLoading(false)}},[]);
 useEffect(()=>{load();if(new URLSearchParams(location.search).get("new")==="1")setShowForm(true)},[load]);
 const filtered=useMemo(()=>items.filter(s=>(filter==="ทั้งหมด"||s.status===filter)&&`${s.name} ${s.contactName} ${s.category} ${s.platform}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
 const set=(k:string,v:string|number)=>setForm(x=>({...x,[k]:v}));
 async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/suppliers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.error);setItems(x=>[d.supplier,...x]);setForm(empty);setShowForm(false)}catch(e){setError(e instanceof Error?e.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}}
 async function updateStatus(id:string,status:string){const old=items;setItems(x=>x.map(s=>s.id===id?{...s,status}:s));const r=await fetch("/api/suppliers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok){setItems(old);setError("เปลี่ยนสถานะไม่สำเร็จ")}}
 async function remove(id:string){if(!confirm("ลบ Supplier รายการนี้หรือไม่?"))return;const r=await fetch(`/api/suppliers?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setItems(x=>x.filter(s=>s.id!==id));else setError("ลบ Supplier ไม่สำเร็จ")}
 return <main className="shell suppliers-shell"><aside className="sidebar"><a className="brand" href="/dashboard"><img src="/wewalldifo-logo.png" alt="WEWALLDIFO Company Limited"/></a><p className="nav-title">เครื่องมือธุรกิจจีน</p><nav>{nav.map(([Icon,label,href],i)=><a key={label} className={i===4?"active":""} href={href}><Icon size={19}/>{label}</a>)}</nav><div className="sidebar-foot"><a href="#"><Settings size={19}/>ตั้งค่า</a><div className="profile"><span>T</span><div><strong>คุณตั้ม</strong><small>VW-000128</small></div></div></div></aside>
 <section className="workspace"><header><div className="mobile-logo"><img src="/wewalldifo-logo.png" alt="WEWALLDIFO"/></div><div className="today-rate"><span>เรท CNY วันนี้</span><b>¥1 = ฿4.65</b><small>อัปเดตล่าสุด 10:35</small></div><a className="account-link" href="/account">บัญชีของฉัน</a></header>
 <div className="suppliers-content"><div className="suppliers-heading"><div><small>SUPPLIER BOOK</small><h1>รายชื่อ Supplier จีน</h1><p>เก็บข้อมูลร้าน คู่ค้า และประวัติความน่าเชื่อถือไว้ในที่เดียว</p></div><button className="new-supplier" onClick={()=>setShowForm(true)}><Plus size={18}/>เพิ่ม Supplier</button></div>
 <section className="supplier-summary"><article><Building2/><div><span>Supplier ทั้งหมด</span><strong>{items.length} ราย</strong></div></article><article><Star/><div><span>คู่ค้าหลัก</span><strong>{items.filter(x=>x.status==="คู่ค้าหลัก").length} ราย</strong></div></article><article><PackageCheck/><div><span>พร้อมใช้งาน</span><strong>{items.filter(x=>["คู่ค้าหลัก","ใช้งานได้"].includes(x.status)).length} ราย</strong></div></article></section>
 {error&&<div className="supplier-error">{error}<button onClick={()=>setError("")}><X size={16}/></button></div>}
 {showForm&&<form className="supplier-form" onSubmit={create}><div className="form-head"><div><h2>เพิ่ม Supplier ใหม่</h2><p>กรอกเฉพาะข้อมูลที่มี แล้วกลับมาเพิ่มเติมภายหลังได้</p></div><button type="button" onClick={()=>setShowForm(false)}><X/></button></div><div className="supplier-fields">
 <label><span>ชื่อร้านหรือโรงงาน *</span><input required value={form.name} onChange={e=>set("name",e.target.value)} placeholder="ชื่อ Supplier จีน"/></label><label><span>ชื่อผู้ติดต่อ</span><input value={form.contactName} onChange={e=>set("contactName",e.target.value)} placeholder="เช่น 王经理"/></label><label><span>แพลตฟอร์ม</span><select value={form.platform} onChange={e=>set("platform",e.target.value)}>{["1688","Taobao","WeChat","Alibaba","โรงงานโดยตรง"].map(x=><option key={x}>{x}</option>)}</select></label><label><span>WeChat / เบอร์ติดต่อ</span><input value={form.contact} onChange={e=>set("contact",e.target.value)} placeholder="WeChat ID หรือเบอร์โทร"/></label><label><span>หมวดสินค้า</span><input value={form.category} onChange={e=>set("category",e.target.value)} placeholder="เช่น ของแต่งบ้าน"/></label><label><span>ลิงก์หน้าร้าน</span><input value={form.shopUrl} onChange={e=>set("shopUrl",e.target.value)} placeholder="https://..."/></label><label><span>คะแนนความน่าเชื่อถือ</span><select value={form.rating} onChange={e=>set("rating",Number(e.target.value))}>{[5,4,3,2,1].map(x=><option value={x} key={x}>{x} ดาว</option>)}</select></label><label><span>สถานะ</span><select value={form.status} onChange={e=>set("status",e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide"><span>หมายเหตุ</span><textarea value={form.note} onChange={e=>set("note",e.target.value)} placeholder="คุณภาพสินค้า เงื่อนไข ราคา หรือประสบการณ์ที่เคยซื้อ"/></label></div><div className="form-actions"><button type="button" onClick={()=>setShowForm(false)}>ยกเลิก</button><button className="submit" disabled={saving}>{saving?<LoaderCircle className="spin" size={17}/>:<Plus size={17}/>}บันทึก Supplier</button></div></form>}
 <section className="supplier-list"><div className="list-tools"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่อร้าน ผู้ติดต่อ หรือหมวดสินค้า"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>ทั้งหมด</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></div>
 {loading?<div className="supplier-empty"><LoaderCircle className="spin"/>กำลังโหลด Supplier</div>:filtered.length===0?<div className="supplier-empty"><Building2/><strong>{items.length?"ไม่พบ Supplier ที่ค้นหา":"ยังไม่มี Supplier"}</strong><span>{items.length?"ลองเปลี่ยนคำค้นหรือสถานะ":"กด “เพิ่ม Supplier” เพื่อบันทึกร้านแรก"}</span></div>:<div className="supplier-grid">{filtered.map(s=><article className="supplier-card" key={s.id}><div className="supplier-card-top"><div className="supplier-avatar">{s.name.slice(0,1).toUpperCase()}</div><div><h2>{s.name}</h2><p>{s.category||"ยังไม่ระบุหมวดสินค้า"}</p></div><button className="delete" onClick={()=>remove(s.id)} aria-label={`ลบ ${s.name}`}><Trash2 size={16}/></button></div><div className="rating" aria-label={`${s.rating} ดาว`}>{[1,2,3,4,5].map(n=><Star key={n} size={15} fill={n<=s.rating?"currentColor":"none"}/>)}</div><dl><div><dt>แพลตฟอร์ม</dt><dd>{s.platform}</dd></div><div><dt>ผู้ติดต่อ</dt><dd>{s.contactName||"—"}</dd></div><div><dt>ช่องทางติดต่อ</dt><dd>{s.contact||"—"}</dd></div></dl>{s.note&&<p className="supplier-note">{s.note}</p>}<div className="supplier-card-foot">{s.shopUrl?<a href={s.shopUrl} target="_blank" rel="noreferrer">เปิดหน้าร้าน</a>:<span/>}<select value={s.status} onChange={e=>updateStatus(s.id,e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div></article>)}</div>}</section></div></section></main>
}
