"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Calculator, FileText, Languages, LayoutDashboard, PackageCheck, Plus, Settings, Truck, WalletCards } from "lucide-react";
import "./dashboard.css";
import "./dashboard-live.css";

type Order={id:string;orderNo:string;supplier:string;productName:string;cnyAmount:number;exchangeRate:number;thaiExtraCost:number;expectedRevenue:number;status:string;createdAt:string};
type Supplier={id:string;name:string;status:string};
type Payment={id:string;cnyAmount:number;status:string};
type Shipment={id:string;estimatedCost:number;status:string};
const money=new Intl.NumberFormat("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2});
const tone=(s:string)=>s==="ถึงไทยแล้ว"?"green":s==="ส่งออกจากจีน"?"gold":s==="รอชำระเงิน"?"gray":"blue";
const nav=[[LayoutDashboard,"Dashboard","/dashboard"],[Calculator,"คำนวณต้นทุน","/"],[PackageCheck,"My China Orders","/orders"],[Languages,"ผู้ช่วยภาษาจีน","/assistant"],[FileText,"Supplier Book","/suppliers"],[WalletCards,"ชำระเงินหยวน","/payments"],[Truck,"ขนส่งจีน–ไทย","/shipping"]] as const;

export default function Dashboard(){
 const [orders,setOrders]=useState<Order[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[payments,setPayments]=useState<Payment[]>([]),[shipments,setShipments]=useState<Shipment[]>([]);
 useEffect(()=>{Promise.all([fetch("/api/orders"),fetch("/api/suppliers"),fetch("/api/payments"),fetch("/api/shipments")]).then(rs=>Promise.all(rs.map(r=>r.json()))).then(([o,s,p,h])=>{setOrders(o.orders||[]);setSuppliers(s.suppliers||[]);setPayments(p.payments||[]);setShipments(h.shipments||[])}).catch(()=>{})},[]);
 const d=useMemo(()=>{const total=orders.reduce((s,o)=>s+o.cnyAmount*o.exchangeRate+o.thaiExtraCost,0),active=orders.filter(o=>!["ถึงไทยแล้ว","ยกเลิก"].includes(o.status)),pending=orders.filter(o=>o.status==="รอชำระเงิน"),revenue=orders.reduce((s,o)=>s+o.expectedRevenue,0);return{total,active:active.length,pending:pending.reduce((s,o)=>s+o.cnyAmount*o.exchangeRate,0),pendingCount:pending.length,profit:revenue-total,count:(status:string)=>orders.filter(o=>o.status===status).length}},[orders]);
 return <main className="shell dashboard-shell"><aside className="sidebar"><a className="brand" href="/dashboard"><img src="/wewalldifo-logo.png" alt="WEWALLDIFO Company Limited"/></a><p className="nav-title">เครื่องมือธุรกิจจีน</p><nav>{nav.map(([Icon,label,href],i)=><a key={label} className={i===0?"active":""} href={href}><Icon size={19}/>{label}{i===2&&orders.length>0&&<em>{orders.length}</em>}</a>)}</nav><div className="sidebar-foot"><a href="#settings"><Settings size={19}/>ตั้งค่า</a><div className="profile"><span>T</span><div><strong>คุณตั้ม</strong><small>VW-000128</small></div></div></div></aside>
 <section className="workspace"><header><div className="mobile-logo"><img src="/wewalldifo-logo.png" alt="WEWALLDIFO"/></div><div className="today-rate"><span>เรท CNY วันนี้</span><b>¥1 = ฿4.65</b><small>อัปเดตล่าสุด 10:35</small></div><button>LINE　บัญชีของฉัน</button></header><div className="dashboard-content">
 <div className="dash-heading"><div><small>DASHBOARD</small><h1>ภาพรวมธุรกิจจีน</h1><p>สรุปออเดอร์ การชำระเงิน Supplier และการขนส่ง</p></div><div className="sample-badge">ข้อมูลจริงจากทุกเมนู</div></div>
 <section className="stat-grid"><Stat title="ต้นทุนออเดอร์ทั้งหมด" value={`฿${money.format(d.total)}`} note={`${orders.length} ออเดอร์ในระบบ`} icon={<WalletCards/>}/><Stat title="Supplier" value={`${suppliers.length}`} note={`${suppliers.filter(s=>s.status==="คู่ค้าหลัก").length} คู่ค้าหลัก`} icon={<FileText/>}/><Stat title="คำขอชำระที่รอดำเนินการ" value={`${payments.filter(p=>!["ชำระสำเร็จ","ยกเลิก"].includes(p.status)).length}`} note={`¥${money.format(payments.filter(p=>!["ชำระสำเร็จ","ยกเลิก"].includes(p.status)).reduce((a,p)=>a+p.cnyAmount,0))}`} warn icon={<WalletCards/>}/><Stat title="พัสดุกำลังเดินทาง" value={`${shipments.filter(s=>s.status==="กำลังขนส่ง").length}`} note={`${shipments.length} พัสดุทั้งหมด`} icon={<Truck/>}/></section>
 <section className="quick-actions"><a href="/orders?new=1"><i><Plus/></i><div><strong>เพิ่มออเดอร์จีน</strong><span>บันทึกรายการสั่งซื้อใหม่</span></div><ArrowUpRight/></a><a href="/payments?new=1"><i><WalletCards/></i><div><strong>สร้างคำขอชำระ</strong><span>ส่งข้อมูลชำระเงินหยวน</span></div><ArrowUpRight/></a><a href="/shipping?new=1"><i><Truck/></i><div><strong>เพิ่มพัสดุจีน</strong><span>คำนวณและติดตามขนส่ง</span></div><ArrowUpRight/></a><a href="/assistant"><i><Languages/></i><div><strong>คุยกับร้านจีน</strong><span>สร้างข้อความจีนพร้อมส่ง</span></div><ArrowUpRight/></a></section>
 <section className="service-strip"><a href="/suppliers"><FileText/><span>Supplier</span><b>{suppliers.length}</b><small>ราย</small></a><a href="/payments"><WalletCards/><span>คำขอชำระ</span><b>{payments.length}</b><small>รายการ</small></a><a href="/shipping"><Truck/><span>พัสดุขนส่ง</span><b>{shipments.length}</b><small>รายการ</small></a><a href="/orders"><PackageCheck/><span>ออเดอร์จีน</span><b>{orders.length}</b><small>รายการ</small></a></section>
 <div className="dashboard-columns"><section className="dash-card spending-card"><div className="card-heading"><div><h2>ยอดซื้อจากจีน</h2><p>ข้อมูลสะสมในระบบ</p></div></div><div className="chart-total"><strong>฿{money.format(d.total)}</strong><span><ArrowUpRight size={14}/> ข้อมูลจริง</span></div><div className="chart" aria-label="กราฟภาพรวม">{[24,38,31,52,66,orders.length?88:8].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{["เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย."][i]}</span></div>)}</div></section>
 <section className="dash-card status-card"><div className="card-heading"><div><h2>งานที่ต้องจัดการ</h2><p>รวมจากทุกส่วนของระบบ</p></div></div><div className="donut"><div><strong>{d.active+payments.filter(p=>!["ชำระสำเร็จ","ยกเลิก"].includes(p.status)).length+shipments.filter(s=>!["ส่งมอบแล้ว","ยกเลิก"].includes(s.status)).length}</strong><span>รายการ</span></div></div><ul><li><i className="dot blue"/>ออเดอร์เปิดอยู่ <b>{d.active}</b></li><li><i className="dot gold"/>คำขอชำระ <b>{payments.filter(p=>!["ชำระสำเร็จ","ยกเลิก"].includes(p.status)).length}</b></li><li><i className="dot green"/>พัสดุยังไม่ส่งมอบ <b>{shipments.filter(s=>!["ส่งมอบแล้ว","ยกเลิก"].includes(s.status)).length}</b></li><li><i className="dot gray"/>Supplier ทดลอง <b>{suppliers.filter(s=>s.status==="กำลังทดลอง").length}</b></li></ul></section></div>
 <section className="dash-card orders-card"><div className="card-heading"><div><h2>ออเดอร์ล่าสุด</h2><p>รายการสั่งซื้อที่มีการเคลื่อนไหวล่าสุด</p></div><a href="/orders">ดูทั้งหมด</a></div>{orders.length===0?<div className="dashboard-empty">ยังไม่มีออเดอร์ — เพิ่มรายการแรกได้ที่ My China Orders</div>:<div className="table-scroll"><table><thead><tr><th>เลขออเดอร์</th><th>Supplier / สินค้า</th><th>ยอดเงิน</th><th>สถานะ</th><th></th></tr></thead><tbody>{orders.slice(0,5).map(o=><tr key={o.id}><td><b>{o.orderNo}</b></td><td><strong>{o.supplier}</strong><span>{o.productName}</span></td><td><b>¥{money.format(o.cnyAmount)}</b></td><td><em className={`status ${tone(o.status)}`}>{o.status}</em></td><td><a href="/orders">ดูรายละเอียด</a></td></tr>)}</tbody></table></div>}</section>
 </div></section></main>;
}
function Stat({title,value,note,icon,up,warn}:{title:string;value:string;note:string;icon:React.ReactNode;up?:boolean;warn?:boolean}){return <article className="stat-card"><div className={`stat-icon ${warn?"warning":""}`}>{icon}</div><span>{title}</span><strong>{value}</strong><small className={up?"up":""}>{up?<ArrowUpRight size={14}/>:warn?<ArrowDownRight size={14}/>:null}{note}</small></article>}
