"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Calculator, FileText, Languages, LayoutDashboard, PackageCheck, Plus, Settings, Truck, WalletCards } from "lucide-react";
import "./dashboard.css";
import "./dashboard-live.css";

type Order={id:string;orderNo:string;supplier:string;productName:string;cnyAmount:number;exchangeRate:number;thaiExtraCost:number;expectedRevenue:number;status:string;createdAt:string};
const money=new Intl.NumberFormat("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2});
const tone=(s:string)=>s==="ถึงไทยแล้ว"?"green":s==="ส่งออกจากจีน"?"gold":s==="รอชำระเงิน"?"gray":"blue";
const nav=[[LayoutDashboard,"Dashboard","/dashboard"],[Calculator,"คำนวณต้นทุน","/"],[PackageCheck,"My China Orders","/orders"],[Languages,"ผู้ช่วยภาษาจีน","/assistant"],[FileText,"Supplier Book","/suppliers"],[WalletCards,"ชำระเงินหยวน","#payment"],[Truck,"ขนส่งจีน–ไทย","#shipping"]] as const;

export default function Dashboard(){
 const [orders,setOrders]=useState<Order[]>([]);
 useEffect(()=>{fetch("/api/orders").then(r=>r.json()).then(d=>setOrders(d.orders||[])).catch(()=>setOrders([]))},[]);
 const d=useMemo(()=>{const total=orders.reduce((s,o)=>s+o.cnyAmount*o.exchangeRate+o.thaiExtraCost,0),active=orders.filter(o=>!["ถึงไทยแล้ว","ยกเลิก"].includes(o.status)),pending=orders.filter(o=>o.status==="รอชำระเงิน"),revenue=orders.reduce((s,o)=>s+o.expectedRevenue,0);return{total,active:active.length,pending:pending.reduce((s,o)=>s+o.cnyAmount*o.exchangeRate,0),pendingCount:pending.length,profit:revenue-total,count:(status:string)=>orders.filter(o=>o.status===status).length}},[orders]);
 return <main className="shell dashboard-shell"><aside className="sidebar"><a className="brand" href="/dashboard"><img src="/wewalldifo-logo.png" alt="WEWALLDIFO Company Limited"/></a><p className="nav-title">เครื่องมือธุรกิจจีน</p><nav>{nav.map(([Icon,label,href],i)=><a key={label} className={i===0?"active":""} href={href}><Icon size={19}/>{label}{i===2&&orders.length>0&&<em>{orders.length}</em>}</a>)}</nav><div className="sidebar-foot"><a href="#settings"><Settings size={19}/>ตั้งค่า</a><div className="profile"><span>T</span><div><strong>คุณตั้ม</strong><small>VW-000128</small></div></div></div></aside>
 <section className="workspace"><header><div className="mobile-logo"><img src="/wewalldifo-logo.png" alt="WEWALLDIFO"/></div><div className="today-rate"><span>เรท CNY วันนี้</span><b>¥1 = ฿4.65</b><small>อัปเดตล่าสุด 10:35</small></div><button>LINE　บัญชีของฉัน</button></header><div className="dashboard-content">
 <div className="dash-heading"><div><small>DASHBOARD</small><h1>ภาพรวมธุรกิจจีน</h1><p>สรุปออเดอร์ ต้นทุน และรายการที่ต้องจัดการ</p></div><div className="sample-badge">อัปเดตจาก My Orders</div></div>
 <section className="stat-grid"><Stat title="ต้นทุนรวมทั้งหมด" value={`฿${money.format(d.total)}`} note={`${orders.length} ออเดอร์ในระบบ`} icon={<WalletCards/>}/><Stat title="ออเดอร์กำลังดำเนินการ" value={`${d.active}`} note="รายการที่ยังไม่ถึงไทย" icon={<PackageCheck/>}/><Stat title="ยอดรอชำระ" value={`฿${money.format(d.pending)}`} note={`${d.pendingCount} รายการ`} warn icon={<FileText/>}/><Stat title="กำไรประมาณการ" value={`฿${money.format(d.profit)}`} note="จากรายรับที่คาดไว้" up={d.profit>=0} icon={<ArrowUpRight/>}/></section>
 <section className="quick-actions"><a href="/"><i><Calculator/></i><div><strong>คำนวณต้นทุน</strong><span>เช็กต้นทุนถึงไทยและกำไร</span></div><ArrowUpRight/></a><a href="/orders?new=1"><i><Plus/></i><div><strong>เพิ่มออเดอร์จีน</strong><span>บันทึกรายการสั่งซื้อใหม่</span></div><ArrowUpRight/></a><a href="/suppliers?new=1"><i><FileText/></i><div><strong>เพิ่ม Supplier</strong><span>บันทึกร้านหรือโรงงานจีน</span></div><ArrowUpRight/></a><a href="/assistant"><i><Languages/></i><div><strong>คุยกับร้านจีน</strong><span>สร้างข้อความจีนพร้อมส่ง</span></div><ArrowUpRight/></a></section>
 <div className="dashboard-columns"><section className="dash-card spending-card"><div className="card-heading"><div><h2>ยอดซื้อจากจีน</h2><p>ข้อมูลสะสมในระบบ</p></div></div><div className="chart-total"><strong>฿{money.format(d.total)}</strong><span><ArrowUpRight size={14}/> ข้อมูลจริง</span></div><div className="chart" aria-label="กราฟภาพรวม">{[24,38,31,52,66,orders.length?88:8].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{["เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย."][i]}</span></div>)}</div></section>
 <section className="dash-card status-card"><div className="card-heading"><div><h2>สถานะออเดอร์</h2><p>ทั้งหมด {orders.length} รายการ</p></div></div><div className="donut"><div><strong>{orders.length}</strong><span>ออเดอร์</span></div></div><ul><li><i className="dot blue"/>กำลังผลิต <b>{d.count("กำลังผลิต")}</b></li><li><i className="dot gold"/>กำลังขนส่ง <b>{d.count("ส่งออกจากจีน")}</b></li><li><i className="dot green"/>ถึงไทยแล้ว <b>{d.count("ถึงไทยแล้ว")}</b></li><li><i className="dot gray"/>รอชำระ <b>{d.count("รอชำระเงิน")}</b></li></ul></section></div>
 <section className="dash-card orders-card"><div className="card-heading"><div><h2>ออเดอร์ล่าสุด</h2><p>รายการสั่งซื้อที่มีการเคลื่อนไหวล่าสุด</p></div><a href="/orders">ดูทั้งหมด</a></div>{orders.length===0?<div className="dashboard-empty">ยังไม่มีออเดอร์ — เพิ่มรายการแรกได้ที่ My China Orders</div>:<div className="table-scroll"><table><thead><tr><th>เลขออเดอร์</th><th>Supplier / สินค้า</th><th>ยอดเงิน</th><th>สถานะ</th><th></th></tr></thead><tbody>{orders.slice(0,5).map(o=><tr key={o.id}><td><b>{o.orderNo}</b></td><td><strong>{o.supplier}</strong><span>{o.productName}</span></td><td><b>¥{money.format(o.cnyAmount)}</b></td><td><em className={`status ${tone(o.status)}`}>{o.status}</em></td><td><a href="/orders">ดูรายละเอียด</a></td></tr>)}</tbody></table></div>}</section>
 </div></section></main>;
}
function Stat({title,value,note,icon,up,warn}:{title:string;value:string;note:string;icon:React.ReactNode;up?:boolean;warn?:boolean}){return <article className="stat-card"><div className={`stat-icon ${warn?"warning":""}`}>{icon}</div><span>{title}</span><strong>{value}</strong><small className={up?"up":""}>{up?<ArrowUpRight size={14}/>:warn?<ArrowDownRight size={14}/>:null}{note}</small></article>}
